name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - content/**
      - quartz_repo
      - src/**
      - cesium-src
      - grammar

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Chicago"
          timezoneMacos: "America/Chicago"
          timezoneWindows: "Central Standard Time"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install
          npm run install-deps

      - name: Build Quartz
        run: npm run build:ci

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz_repo/public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
